# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8a0a8f8272844d29d1612b756a67b5c37ac0557cf157f0b98c0d3e3e1f72a2d72251fa07448b94876315e9cabeac450fcf2538760705f21e9f74103ca8a7785

test:
  secret_key_base: 1a67f707fa0444902a6f304050ee0f85021c3e8fafaededb16f578a5a6e02eb04b166c02252624b3b80543999eb06fab19be7ccb65c2008078c1e0509367b73b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1a67f707fa0444902a6f304050ee0f85021c3e8fafaededb16f578a5a6e02eb04b166c02252624b3b80543999eb06fab19be7ccb65c2008078c1e0509367b73b
