source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2'
# Use sqlite3 as the database
#gem 'sqlite3', '1.3.11'

# Use mysql2 as the database
gem 'mysql2', '~> 0.3.18'
# Use SCSS for stylesheets
gem 'sass-rails', '5.0.6'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails','4.2'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks','2.5.3'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
# devise login gem
gem 'devise','3.5.6'
# uploader
gem 'carrierwave','0.10.0'

gem 'remotipart', '~> 1.2'

gem 'mini_magick','4.4.0'

gem 'sprockets','~> 3.0'
# New Relic Analitycs
gem 'newrelic_rpm', '3.15.0.314'
# Kaminari Pagination
gem 'kaminari', '0.16.3'
# Rollbar
gem 'rollbar'
gem 'oj', '~> 2.12.14'
# facebook login
gem 'omniauth-facebook', '~> 4.0'
# google login
gem 'omniauth-google-oauth2'
# Schema to Scaffold
gem 'schema_to_scaffold'
# CUSTOM YOUR GEMS
